InfoVideo/Models/Edition.cs
namespace InfoVideo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Edition")]
    public partial class Edition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Edition()
        {
            History = new HashSet<History>();
        }

        public int Id { get; set; }

        public int? IdVideo { get; set; }

        public int? IdFormat { get; set; }

        [Column(TypeName = "money")]
        public decimal? Price { get; set; }

        [StringLength(30)]
        public string Box { get; set; }

        public virtual Format Format { get; set; }

        public virtual Video Video { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> History { get; set; }
    }
}

InfoVideo/Models/Format.cs
namespace InfoVideo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Format")]
    public partial class Format
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Format()
        {
            Edition = new HashSet<Edition>();
        }

        public int Id { get; set; }

        [Required]
        [StringLength(20)]
        public string Container { get; set; }

        [Required]
        [StringLength(20)]
        public string Languages { get; set; }

        public bool? Support3D { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Edition> Edition { get; set; }
    }
}

InfoVideo/Models/Helpers.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using System.Security.Principal;
using System.Web;

namespace InfoVideo.Models
{


    public class LoginModel
    {
        [Required]
        [StringLength(20)]
     

        public string Login { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [StringLength(20)]

        [DisplayName("Пароль")]


        public string Password { get; set; }
    }


    public sealed class MyDbInitializer : DropCreateDatabaseIfModelChanges<InfoVideoEntities>
    {
        private string[] addr_s = {"Багдановіча", "Кульман", "Вітаўта", "Альгерда"};
        private string[] city = { "Мінск, ", "Віцебск, ", "Гародня, ", "Магілёў, " };
        private string[] name = { "Алесь", "Генадзь", "Віталь", "Пятро","Раман","Марыя","Юлія","Зміцер" };
        private string[] em = { "@mail.ru", "@gmail.com", "@yandex.com" };
        private string[] ln = { "Прыгожы", "Лепшы", "Добры" };
        private string[] boxs = { "Дыск DVD", "Дыск BlueRay", "USB-Flash","Дыск mini-DVD" };

        Random r = new Random();

        protected override void Seed(InfoVideoEntities context)
        {

   


            var adminR = new Roles { Name = "Administrator" };
            var userR = new Roles { Name = "User" };

            context.Roles.Add(adminR);
            context.Roles.Add(userR);
                    
            var admin = new Users { Email = "asd@mail1.ru", FirstName = "Leon", LastName = "Budkouski", Password = "Asd123",Login = "Hienadz", Address = "Мінск, Кульман 33", Discount  = 10,Roles = adminR};
            var user = new Users { Email = "kross@mail.ru", FirstName = "Dylan", LastName = "Kross", Password = "Asd111", Login = "HienadzA", Address = "Мінск, Багдановіча М 100", Discount = 0, Roles = userR};

            for (int i = 0; i < 10; i++)
            {
                var ff = name[r.Next(0, 100)%name.Length];
                var c = new Users
                {
                   Address = city[r.Next(0,100)%city.Length]  + addr_s[r.Next(0, 100) % addr_s.Length] + " " + r.Next(0, 100),
                   Discount = (short?) r.Next(0,40),
                   FirstName = ff,
                   Email = ff + r.Next(80, 99) + em[r.Next(0, 100) % em.Length],
                   Password = ff + r.Next(0, 10000)          ,
                   Roles = userR,
                   LastName = ln[r.Next(0, 100) % ln.Length]      ,
                    Login =         ff +r.Next(0,100)

                };
                context.Users.Add(c);
            }

            context.Users.Add(admin);
            context.Users.Add(user);
       

     

            Video v = new Video {Title = "The 100 - Season 3",
                Description = "Пасля ядзернай вайны прайшло 97 гадоў. " +
                              "Рэшткі чалавецтва, якія хаваюцца на касмічнай станцыі «Каўчэг»," +
                              " пакутуюць ад недахопу рэсурсаў, неабходных для далейшага выжывання. " +
                              "Урад вычарпаў усе меры, уключаючы цвёрдае абмежаванне нараджальнасці, " +
                              "але сітуацыя працягвае пагаршацца. Застаецца адзінае выйсце — паспрабаваць вярнуцца на Зямлю. " +
                              "Каб пазнаць, ці прыдатная для жыцця пакінутая даўным-даўно планета, " +
                              "урад адпраўляе туды сотню маладых правапарушальнікаў, у ліку дзецей высокапастаўленых службоўцаў" +
                              " і іншых вядомых на «Каўчэгу» людзей. " +
                              "Зараз лёс усяго чалавецтва залежыць ад гэтай групы «выгнаннікаў»",
                                Date = new DateTime(2014,01,01),
                                Genre = "Фантастыка",
                                Logo = "the100.png"

            };

            Video v1 = new Video
            {
                Title = "The Shannara Chronicles",
                Description = "Канал MTV прадстаўляе фэнтэзі-серыял «Хронікі Шаннары»," +
                              " у аснову якога лёг аднайменны цыкл раманаў фантаста Тэры Брукса. " +
                              "Сам пісьменнік прымаў актыўны ўдзел у адаптацыі сваіх твораў для маленькіх экранаў," +
                              " а таму знатакі яго творчасці цалкам могуць разлічваць на тое, " +
                              "што тэлевізійная версія «Харонікі Шаннары» будзе максімальна адпавядаць першакрыніцы. " +
                              "З моманту публікацыі кніг Брукса прайшло нямала часу, " +
                              "але менавіта цяпер развіццё тэхналогій і наяўныя ў тэлебачання магчымасці, " +
                              "па меркаванні аўтара і прадзюсараў праекта, дазволяць займальна і ў " +
                              "поўнай меры перанесці фантастычны свет пісьменніка на экраны. " +
                              "Гледачоў чакае незабыўнае вандраванне па Чатырох Землях, населеным дзіўнымі істотамі, " +
                              "а візуальны складнік пацешыць нават самых прыдзірлівых серыяламанаў.",
                Date = new DateTime(2015, 05, 07),
                Genre = "Прыгоды, фантастыка",
                Logo = "shannar.jpg"

            };


            Video v2 = new Video
            {
                Title = "The Black List",
                Description = "An FBI fugitive, Raymond \"Red\" Reddington (Spader), joins the FBI in an attempt to work"+
                                " together and bring down criminals and terrorists. After their first victory, "+
                                "a list of dangerous but unknown criminals is revealed by Red. "+
                                    "With the help of a rookie FBI profiler, Red will work to eliminate all those in \"The List\"",
                Date = new DateTime(2014, 02, 01),
                Genre = "Шпіёнскі",
                Logo = "the-blacklist.jpg"

            };


            Video v3 = new Video
            {
                Title = "Chicago Fire",
                Description = "Chicago Fire is an American action-drama television series that airs on NBC and was created " +
                              "by Michael Brandt and Derek Haas with Dick Wolf serving as an executive producer. " +
                              "The series originally premiered on October 10, 2012. The show follows the lives of the firefighters" +
                              " and paramedics working at the Chicago Fire Department at the firehouse of Engine 51, Truck 81, Squad 3," +
                              " Ambulance 61 and Battalion 25. The pilot episode had an early release at NBC.com, " +
                              "before the series' premiere on television.",
                Date = new DateTime(2014, 06, 21),
                Genre = "Пажарныя",
                Logo = "fire-key-art.jpg"

            };


            context.Video.Add(v);
            context.Video.Add(v1);
            context.Video.Add(v2);
            context.Video.Add(v3);

            Format f= new Format {Languages = "Bel, En, De", Container = "mkv", Support3D = false};
            Format f1 = new Format { Languages = "Bel, En", Container = "mp4", Support3D = true };
            Format f2 = new Format { Languages = "En", Container = "3gp", Support3D = false };
            Format f3 = new Format { Languages = "De", Container = "avi", Support3D = true };

            context.Format.Add(f);
            context.Format.Add(f1);
            context.Format.Add(f2);
            context.Format.Add(f3);

            context.SaveChanges();

            for (int i = 0; i < 15; i++)
            {
                var ee = new Edition();

                ee.Box = boxs[r.Next(0, 100) % boxs.Length];
                ee.Price = r.Next(20, 800)*1000;
                ee.Video = context.Video.ToList().ElementAt(r.Next(0, context.Video.Count() ));
                ee.Format = context.Format.ToList().ElementAt(r.Next(0, context.Format.Count() ));
              

                context.Edition.Add(ee);
            }

            Edition e = new Edition {Box = "Діск BluRay", Format = f, Price = 130000, Video = v};
            Edition e1 = new Edition { Box = "Діск DVD", Format = f1, Price = 30000, Video = v1 };
            Edition e2 = new Edition { Box = "Діск BluRay", Format = f1, Price = 30000, Video = v };

            context.Edition.Add(e);
            context.Edition.Add(e1);
            context.Edition.Add(e2);

            History h = new History {Date = DateTime.Now, Edition = e,Users = admin};
            History h1 = new History { Date = DateTime.Today, Edition = e1, Users = user };

            context.History.Add(h);
            context.History.Add(h1);

            context.SaveChanges();

            DateTime start = new DateTime(2015, 1, 1);
            int range = (DateTime.Today - start).Days;

            for (int i = 0; i < 20; i++)
            {
                var hh = new History {

                       
                

                Date = start.AddDays(r.Next(range)),

                Edition = context.Edition.ToList().ElementAt(r.Next(0, context.Edition.Count())),

                    Users = context.Users.ToList().ElementAt(r.Next(0, context.Users.Count()))
                };

                context.History.Add(hh);

            }
        
            context.SaveChanges();
            base.Seed(context);
        }
    }
}

InfoVideo/Models/History.cs
namespace InfoVideo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("History")]
    public partial class History
    {
        public int Id { get; set; }

        public int? IdUser { get; set; }

        public int? IdEdition { get; set; }

        [Column(TypeName = "datetime2")]
        public DateTime Date { get; set; }

        [Column(TypeName = "money")]
        public decimal Price { get; set; }

        public virtual Edition Edition{ get; set; }

        public virtual Users Users { get; set; }

        public void CalculatePriceBuy()
        {
            if (Edition.Price.HasValue && Users.Discount.HasValue)
            {
                Price = Edition.Price.Value*(1-Users.Discount.Value);
            }
        }
    }
}

InfoVideo/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

InfoVideo/Controllers/EditionsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using InfoVideo.Models;


namespace InfoVideo.Controllers
{
    public class EditionsController : Controller
    {
        private readonly InfoVideoEntities _db = new InfoVideoEntities();

   
        public async Task<ActionResult> Index()
        {
            var edition = _db.Edition.Include(e => e.Format).Include(e => e.Video); ;

            return View(await edition.ToListAsync());
        }


        public ActionResult Details(int? id)
        {
            return RedirectToAction("Details", "Videos", new { id });

        }


        public ActionResult Create()
        {
            if (User.IsInRole("Administrator"))
            {
                ViewBag.IdFormat = new SelectList(_db.Format, "Id", "Container");
                ViewBag.IdVideo = new SelectList(_db.Video, "Id", "Title");
                return View();
            }
            return PartialView("AuthAdminError");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,IdVideo,IdFormat,Price,Box")] Edition edition)
        {
            if (User.IsInRole("Administrator"))
            {
                if (ModelState.IsValid)
                {
                 
                    _db.Edition.Add(edition);
                    await _db.SaveChangesAsync();
        
                return RedirectToAction("Index");
            }

            ViewBag.IdFormat = new SelectList(_db.Format, "Id", "Container", edition.IdFormat);
            ViewBag.IdVideo = new SelectList(_db.Video, "Id", "Title", edition.IdVideo);

            return View(edition);
            }
            return PartialView("AuthAdminError");
        }

      
        public async Task<ActionResult> Edit(int? id)
        {
            if (User.IsInRole("Administrator"))
            {
                if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Edition edition = await _db.Edition.FindAsync(id);
            if (edition == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdFormat = new SelectList(_db.Format, "Id", "Container", edition.IdFormat);
            ViewBag.IdVideo = new SelectList(_db.Video, "Id", "Title", edition.IdVideo);
            return View(edition);
            }
            return PartialView("AuthAdminError");
        }
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,IdVideo,IdFormat,Price,Box")] Edition edition)
        {
            if (User.IsInRole("Administrator"))
            {
                if (ModelState.IsValid)
            {


                    _db.Entry(edition).State =  EntityState.Modified;

                    var c = await _db.SaveChangesAsync();

                    if (c == 1)
                        return RedirectToAction("Index");  
                
            }
            ViewBag.IdFormat = new SelectList(_db.Format, "Id", "Container", edition.IdFormat);
            ViewBag.IdVideo = new SelectList(_db.Video, "Id", "Title", edition.IdVideo);
            return View(edition);
            }
            return PartialView("AuthAdminError");
        }


        public async Task<ActionResult> Delete(int? id)
        {
            if (User.IsInRole("Administrator"))
            {
                if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Edition edition = await _db.Edition.FindAsync(id);
            if (edition == null)
            {
                return HttpNotFound();
            }
            return View(edition);
            }
            return PartialView("AuthAdminError");
        }

       
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            if (User.IsInRole("Administrator"))
            {
                var c = await _db.Edition.FindAsync(id);

                _db.Edition.Remove(c);

         
                return RedirectToAction("Index");
         
            }
            return PartialView("AuthAdminError");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

InfoVideo/Views/Editions/Create.cshtml
@model InfoVideo.Models.Edition

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Стварыць</h3>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Новае выданне</h4>
    
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdVideo, "IdVideo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdVideo", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdVideo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdFormat, "IdFormat", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdFormat", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdFormat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Box, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Box, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Box, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default green" />
            </div>
        </div>
    </div>
}

InfoVideo/Views/Editions/Delete.cshtml
@model InfoVideo.Models.Edition

@{
    ViewBag.Title = "Выдаленне";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Вы ўпэўнены, што хочаце выдаліць?</h4>

<div>

    @{
        Html.RenderPartial("Edition", Model);
    }




    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Выдаліць" class="btn btn-default red" />
        </div>
    }
</div>

InfoVideo/Views/Editions/Details.cshtml
@model InfoVideo.Models.Edition

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Падрабязнасці</h3>



@{
   Html.RenderPartial("Edition",Model);
}

InfoVideo/Views/Editions/Edit.cshtml
@model InfoVideo.Models.Edition

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Змяненне</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">


        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.IdVideo, "IdVideo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdVideo", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdVideo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdFormat, "IdFormat", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdFormat", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdFormat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Box, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Box, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Box, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Захаваць" class="btn btn-default green" />
            </div>
        </div>
    </div>
}

InfoVideo/Views/Editions/Edition.cshtml
@using System.Web.Mvc.Ajax
@model InfoVideo.Models.Edition

<div class="card">

    @Html.HiddenFor(model => model.Id)
    @Html.AntiForgeryToken()

   <h2>Выданне</h2>

    <div class="from-form">
        <i class="fa fa-cube" aria-hidden="true"></i>
        @Html.DisplayFor(model => model.Box)
    </div>

    <i class="zmdi zmdi-menu menu-switch"></i>
    <div class="from-form">
        <i class="zmdi zmdi-file"></i>
        @Html.DisplayFor(model => model.Format.Container)
    </div>


    <div class="from-form">
        <i class="zmdi zmdi-movie-alt"></i>
        @Html.DisplayFor(model => model.Video.Title)
    </div>


    <div class="from-form">
        <i class="fa fa-money" aria-hidden="true"></i>
        @Html.DisplayFor(model => model.Price)
    </div>

    <div class="menu-list card-menu" style="display: none">
        <ul>
            <a href="@Url.Action("Details", "Videos", new {id = Model.Id})">
                <i class="zmdi zmdi-view-list-alt zmdi-hc-fw"></i>Падрабязнасці
            </a>
            <a href="@Url.Action("Edit", "Videos", new {id = Model.Id})">
                <i class="zmdi zmdi-edit zmdi-hc-fw"></i>Змяніць
            </a>
            <a href="@Url.Action("Delete", "Videos", new {id = Model.Id})">
                <i class="zmdi zmdi-delete zmdi-hc-fw"></i>Выдаліць
            </a>
        </ul>

    </div>



</div>

InfoVideo/Views/Editions/Index.cshtml
@model IEnumerable<InfoVideo.Models.Edition>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Выданні</h2>
@if (User.IsInRole("Administrator"))
{
    <p>
        <a href="@Url.Action("Create", "Editions")" class="btn btn-logo gray" title="Стварыць выданне">
            <i class="zmdi zmdi-plus-circle zmdi-hc-fw"></i>
            Стварыць новае
        </a>
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Format.Container)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Video.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Box)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Format.Container)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Video.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Box)
        </td>
        <td>
            <a href="@Url.Action("Edit", "Editions", new {id = item.Id})" title="Змяніць">
                <i class="zmdi zmdi-edit zmdi-hc-fw"></i>
            </a>
            <a href="@Url.Action("Details", "Editions", new {id = item.Id})" title="Падрабязнасці">
                <i class="zmdi zmdi-eye zmdi-hc-fw"></i>
            </a>
            <a href="@Url.Action("Delete","Editions", new { id = item.Id })" title="Выдаліць">
                <i class="zmdi zmdi-delete zmdi-hc-fw"></i>
            </a>
        </td>
    </tr>
}

</table>

InfoVideo/Views/Editions/Model.cshtml
@using System.Web.Mvc.Ajax
@model InfoVideo.Models.Edition

@using (Html.BeginForm("Buy", "Account"))
{

                <div class="card" >

                    @Html.HiddenFor(model => model.Id)
                    @Html.AntiForgeryToken()

                    <i style="display: none" class="fa fa-circle-o-notch fa-spin fa-3x fa-fw margin-bottom anim"></i>

                    <h2>@Model.Box</h2>

                    <div class="from-form">
                        <i class="fa fa-language" aria-hidden="true"></i>
                        @Html.DisplayFor(model => model.Format.Languages)
                    </div>
                    <i class="zmdi zmdi-menu menu-switch"></i>
                    <div class="from-form">
                        <i class="zmdi zmdi-file"></i>
                        @Html.DisplayFor(model => model.Format.Container)
                    </div>


                    <div class="from-form">
                        <i class="zmdi zmdi-3d-rotation"></i>
                        @Html.DisplayNameFor(model => model.Format.Support3D)
                        @Html.DisplayFor(model => model.Format.Support3D)
                    </div>



                    <div class="from-form">
                        <i class="fa fa-money" aria-hidden="true"></i>
                        @Html.DisplayFor(model => model.Price)
                    </div>

                    <div class="menu-list card-menu"  style="display: none">
                        <ul>
                            <a href="@Url.Action("Details", "Videos", new {id = Model.Id})">
                                <i class="zmdi zmdi-view-list-alt zmdi-hc-fw"></i>Падрабязнасці
                            </a>
                            <a href="@Url.Action("Edit", "Videos", new {id = Model.Id})">
                                <i class="zmdi zmdi-edit zmdi-hc-fw"></i>Змяніць
                            </a>
                            <a href="@Url.Action("Delete", "Videos", new {id = Model.Id})">
                                <i class="zmdi zmdi-delete zmdi-hc-fw"></i>Выдаліць
                            </a>
                        </ul>

                    </div>

                 
                    <a onclick="buy(this)" class="main" title="Набыць">
                        <i class="zmdi zmdi-shopping-cart-plus zmdi-hc-fw"></i>Набыць
                    </a>


                </div>

 

}