InfoVideo/Models/Format.cs
namespace InfoVideo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Format")]
    public partial class Format
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Format()
        {
            Edition = new HashSet<Edition>();
        }

        public int Id { get; set; }

        [Required]
        [StringLength(20)]
        public string Container { get; set; }

        [Required]
        [StringLength(20)]
        public string Languages { get; set; }

        public bool? Support3D { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Edition> Edition { get; set; }
    }
}

InfoVideo/Models/History.cs
namespace InfoVideo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("History")]
    public partial class History
    {
        public int Id { get; set; }

        public int? IdUser { get; set; }

        public int? IdEdition { get; set; }

        [Column(TypeName = "datetime2")]
        public DateTime Date { get; set; }

        [Column(TypeName = "money")]
        public decimal Price { get; set; }

        public virtual Edition Edition{ get; set; }

        public virtual Users Users { get; set; }

        public void CalculatePriceBuy()
        {
            if (Edition.Price.HasValue && Users.Discount.HasValue)
            {
                Price = Edition.Price.Value*(1-Users.Discount.Value);
            }
        }
    }
}

InfoVideo/Controllers/FormatsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using InfoVideo.Models;

namespace InfoVideo.Controllers
{
    public class FormatsController : Controller
    {
        private readonly InfoVideoEntities _db = new InfoVideoEntities();

      
        public async Task<ActionResult> Index()
        {
            return View(await _db.Format.ToListAsync());
        }

        
        public async Task<ActionResult> Details(int? id)
        {
            if (User.IsInRole("Administrator"))
            {
                if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Format format = await _db.Format.FindAsync(id);
            if (format == null)
            {
                return HttpNotFound();
            }
            return View(format);
            }
            return PartialView("AuthAdminError");
        }

      
        public ActionResult Create()
        {
            if (User.IsInRole("Administrator"))
            {
                return View();
            }
            return PartialView("AuthAdminError");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> Create([Bind(Include = "Id,Container,Languages,Support3D")] Format format)
        {
            if (ModelState.IsValid)
            {
                if (
                    _db.Format.FirstOrDefault(
                        t =>
                            t.Container == format.Container && t.Languages == format.Languages &&
                            t.Support3D == format.Support3D) != null)
                {
                    ModelState.AddModelError("","Ужо існуе");
                    return View(format);
                }
                _db.Format.Add(format);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(format);
        }

     
        public async Task<ActionResult> Edit(int? id)
        {
            if (User.IsInRole("Administrator"))
            {
                if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Format format = await _db.Format.FindAsync(id);
            if (format == null)
            {
                return HttpNotFound();
            }
            return View(format);
            }
            return PartialView("AuthAdminError");
        }

    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Container,Languages,Support3D")] Format format)
        {
            if (User.IsInRole("Administrator"))
            {
                if (ModelState.IsValid)
            {
                _db.Entry(format).State = System.Data.Entity.EntityState.Modified;
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(format);
            }
            return PartialView("AuthAdminError");
        }

      
        public async Task<ActionResult> Delete(int? id)
        {
            if (User.IsInRole("Administrator"))
            {
                if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Format format = await _db.Format.FindAsync(id);
            if (format == null)
            {
                return HttpNotFound();
            }
            return View(format);
            }
            return PartialView("AuthAdminError");
        }

       
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            if (User.IsInRole("Administrator"))
            {
                Format format = await _db.Format.FindAsync(id);
                if (format.Edition.Count > 0)
                {
                    ModelState.AddModelError("","Выдаліце залежнасці ад гэтага фармату");
                    return View(format);
                }
            _db.Format.Remove(format);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
            }
            return PartialView("AuthAdminError");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

InfoVideo/Controllers/HistoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using InfoVideo.Models;
using Newtonsoft.Json;

namespace InfoVideo.Controllers
{
    public class HistoriesController : Controller
    {
        private readonly InfoVideoEntities _db = new InfoVideoEntities();


        public async Task<ActionResult> Index()
        {
            if (User.IsInRole("Administrator"))
            {
                var history = _db.History.Include(h => h.Edition).Include(h => h.Users);
                return View(await history.ToListAsync());
            }
            else
            {
                var history = _db.History.Where(t => t.Users.Login == User.Identity.Name)
                            .Include(h => h.Edition)
                            .Include(h => h.Users);

                return View(await history.ToListAsync());
            }
        }


        public async Task<ActionResult> Statistics()
        {
            if (User.IsInRole("Administrator"))
            {
               
                return View();
            }
            else
            {

                return PartialView("AuthAdminError");
            }
        }



        public string GetByDate(int yearDisplay = 2016)
        {
            DateTimeFormatInfo mfi = new DateTimeFormatInfo();
            var b = _db.History.Include(t => t.Edition).GroupBy(t => t.Date).ToList();

            var y = _db.History.Min(t => t.Date.Year);

            var changesPerYearAndMonth =

            from month in Enumerable.Range(1, 12)
            let key = new { Year = yearDisplay, Month = month }
            join revision in b on key
                      equals new
                      {
                          revision.Key.Year,
                          revision.Key.Month
                      } into g
            select new { key.Year, Month = mfi.GetMonthName(key.Month), Count = g.Count() };


            var c = JsonConvert.SerializeObject(changesPerYearAndMonth, Formatting.Indented,
                        new JsonSerializerSettings
                        {
                            PreserveReferencesHandling = PreserveReferencesHandling.Objects
                        });

            return c;

        }


        public string GetByVideo(int yearDisplay = 2016)
        {

            var b = _db.History.GroupBy(t => t.Edition.Video.Title).Select(
                group => new {
                    Title = group.Key,
                    Count = group.Count()
                }).ToList();



            var c = JsonConvert.SerializeObject(b, Formatting.Indented,
                        new JsonSerializerSettings
                        {
                            PreserveReferencesHandling = PreserveReferencesHandling.Objects
                        });

            return c;

        }


        public string GetByUser(int yearDisplay = 2016)
        {

            var b = _db.History.GroupBy(t => t.Users.Login).Select(
                group => new {
                    Login = group.Key,
                    Count = group.Count()
                }).ToList();



            var c = JsonConvert.SerializeObject(b, Formatting.Indented,
                        new JsonSerializerSettings
                        {
                            PreserveReferencesHandling = PreserveReferencesHandling.Objects
                        });

            return c;

        }


        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            History history = await _db.History.FindAsync(id);

            if (history == null)
            {
                return HttpNotFound();
            }

            var u = _db.Users.FirstOrDefault(t => t.Login == User.Identity.Name);

            if (u != null || User.IsInRole("Administrator"))

                return View(history);

            return PartialView("AuthAdminError");
        }







        public async Task<ActionResult> Edit(int? id)
        {

            if (User.IsInRole("Administrator"))
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                History history = await _db.History.FindAsync(id);
                if (history == null)
                {
                    return HttpNotFound();
                }
                ViewBag.IdEdition = new SelectList(_db.Edition, "Id", "Box", history.IdEdition);
                ViewBag.IdUser = new SelectList(_db.Users, "Id", "Login", history.IdUser);
                return View(history);
            }
            return PartialView("AuthAdminError");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,IdUser,IdEdition,Date")] History history)
        {
            if (User.IsInRole("Administrator"))
            {
                if (ModelState.IsValid)
                {
                    _db.Entry(history).State = System.Data.Entity.EntityState.Modified;
                    await _db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                ViewBag.IdEdition = new SelectList(_db.Edition, "Id", "Box", history.IdEdition);
                ViewBag.IdUser = new SelectList(_db.Users, "Id", "Login", history.IdUser);
                return View(history);
            }
            return PartialView("AuthAdminError");
        }




        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

InfoVideo/Controllers/VideosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using InfoVideo.Models;

namespace InfoVideo.Controllers
{
    public class VideosController : Controller
    {
        private readonly InfoVideoEntities _db = new InfoVideoEntities();

        public async Task<ActionResult> Index()
        {

            return View(await _db.Video.ToListAsync());
        }

        
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Video video = await _db.Video.FindAsync(id);
            
            if (video == null)
            {
                return HttpNotFound();
            }
            return View(video);
        }

     
        public ActionResult Create()
        {
            if (User.IsInRole("Administrator"))
            {
                return View();
            }
            return PartialView("AuthAdminError");
        }

        public void ProcessFile(HttpPostedFileBase file, Video video)
        {
            if (file != null && file.ContentLength > 0)

            {
                string path = Path.Combine(Server.MapPath("~/Media/Images"),
                    Path.GetFileName(file.FileName));

                file.SaveAs(path);

                video.Logo = Path.GetFileName(file.FileName);
            }


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Title,Description,Country,Genre")] Video video, HttpPostedFileBase Logo)
        {
            if (User.IsInRole("Administrator"))
            {
                if (ModelState.IsValid)
            {
                
                ProcessFile(Logo, video);

                _db.Video.Add(video);
              await _db.SaveChangesAsync();

              
                return RedirectToAction("Index");
            }

            return View(video);
            }
            return PartialView("AuthAdminError");
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file)
        {
           
            return View();
        }

 
        public async Task<ActionResult> Edit(int? id)
        {
            if (User.IsInRole("Administrator"))
            {
                if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Video video = await _db.Video.FindAsync(id);
            if (video == null)
            {
                return HttpNotFound();
            }
            return View(video);
            }
            return PartialView("AuthAdminError");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Title,Description,Date,Genre")] Video video, HttpPostedFileBase Logo)
        {
            if (User.IsInRole("Administrator"))
            {
                if (ModelState.IsValid)
            {
                _db.Entry(video).State = System.Data.Entity.EntityState.Modified;
                ProcessFile(Logo, video);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(video);
            }
            return PartialView("AuthAdminError");
        }

      
        public async Task<ActionResult> Delete(int? id)
        {
            if (User.IsInRole("Administrator"))
            {
                if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Video video = await _db.Video.FindAsync(id);
            if (video == null)
            {
                return HttpNotFound();
            }
            return View(video);
            }
            return PartialView("AuthAdminError");
        }

 
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            if (User.IsInRole("Administrator"))
            {
                Video video = await _db.Video.FindAsync(id);
                if (video.Edition.Count > 0)
                {
                    ModelState.AddModelError("", "Выдаліце залежнасці ад гэтага відыё");
                    return View(video);
                }
                _db.Video.Remove(video);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
            }
            return PartialView("AuthAdminError");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

InfoVideo/Views/Shared/AuthAdminError.cshtml
@{
    ViewBag.Title = "Доступ забаронены";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Доступ дазволены для адміністратара, нажаль вам бракуе правоў доступа!</h3>

InfoVideo/Views/Shared/Format.cshtml
@model InfoVideo.Models.Format

<div class="card">

    @Html.HiddenFor(model => model.Id)
    @Html.AntiForgeryToken()

    <i style="display: none" class="fa fa-circle-o-notch fa-spin fa-3x fa-fw margin-bottom anim"></i>

    <h2>Фармат</h2>

    <div class="from-form">
        <i class="fa fa-language" aria-hidden="true"></i>
        @Html.DisplayFor(model => model.Languages)
    </div>
    <i class="zmdi zmdi-menu menu-switch"></i>
    <div class="from-form">
        <i class="zmdi zmdi-file"></i>
        @Html.DisplayFor(model => model.Container)
    </div>


    <div class="from-form padding-last">
        <i class="zmdi zmdi-3d-rotation"></i>
        @Html.DisplayNameFor(model => model.Support3D)
        @Html.DisplayFor(model => model.Support3D)
    </div>



    <div class="menu-list card-menu" style="display: none">
        <ul>
            <a href="@Url.Action("Details", "Formats", new {id = Model.Id})">
                <i class="zmdi zmdi-view-list-alt zmdi-hc-fw"></i>Падрабязнасці
            </a>
            <a href="@Url.Action("Edit", "Formats", new {id = Model.Id})">
                <i class="zmdi zmdi-edit zmdi-hc-fw"></i>Змяніць
            </a>
            <a href="@Url.Action("Delete", "Formats", new {id = Model.Id})">
                <i class="zmdi zmdi-delete zmdi-hc-fw"></i>Выдаліць
            </a>
        </ul>

    </div>



</div>

InfoVideo/Views/Shared/Header.cshtml
@using System.Web.Mvc.Html
@using InfoVideo.Models
<div class="logo">
    <div class="logo-text" onclick="location.href = '@Url.Action("Index", "Home")'">
        Hienadź Budkoŭski
    </div>
    <img id="img" class="logo-img" src="/Media/Images/movie.png" alt="" />
</div>
<div class="header-menu right">
    <ul>

        @if (User.IsInRole("Administrator"))
        {
            <li>
                <a href="@Url.Action("Index", "Home")" title="Дамоў">
                    Працэдуры
                    <i class="zmdi zmdi-settings zmdi-hc-lg"></i>
                </a>
                <ul>
                    <li>
                        <a href="@Url.Action("Proc", "Home")">
                            ProcType
                            <i class="zmdi  zmdi-view-list-alt zmdi-hc-lg"></i>
                        </a>
                    </li>

                </ul>
            </li>
        }
        @if (User.Identity.IsAuthenticated)
        {
            if (User.IsInRole("Administrator"))
            {

                <li>
                    <a href="@Url.Action("Index", "Account")" title="Карыстачы">
                        Карыстачы
                        <i class="zmdi zmdi-accounts-list zmdi-hc-lg"></i>
                    </a>

                    <ul>
                        <li>
                            <a href="@Url.Action("Index", "Roles")">
                                Ролі
                                <i class="zmdi   zmdi-filter-list zmdi-hc-lg"></i>
                            </a>
                        </li>

                    </ul>
                </li>
            }
            <li class="menu-breit">
                <a href="@Url.Action("Index", "Histories")" title="Гісторыя">
                    Гісторыя
                    <i class="fa fa-history" aria-hidden="true"></i>
                </a>

                @if (User.IsInRole("Administrator"))
                {
                    <ul>
                        <li>
                            <a href="@Url.Action("Statistics", "Histories")">
                                Статыстыка
                                <i class="zmdi   zmdi-filter-list zmdi-hc-lg"></i>
                            </a>
                        </li>

                    </ul>
                }
            </li>
        }

        <li>
            <a href="@Url.Action("Index", "Home")" title="Дамоў">
                Выданні
                <i class="zmdi zmdi-codepen zmdi-hc-lg"></i>
            </a>

            <ul>
                <li>
                    <a href="@Url.Action("Index", "Editions")">
                        Спіс
                        <i class="zmdi  zmdi-view-list-alt zmdi-hc-lg"></i>
                    </a>
                </li>
                @if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
                {
                    <li>
                        <a href="@Url.Action("Create", "Editions")">
                            Стварыць
                            <i class="zmdi zmdi-plus-circle zmdi-hc-lg"></i>
                        </a>
                    </li>
                }
            </ul>
        </li>
        @if (User.Identity.IsAuthenticated)
        {
            <li>
                <a href="@Url.Action("Index", "Home")" title="Дамоў">
                    Фарматы
                    <i class="zmdi zmdi-file zmdi-hc-lg"></i>
                </a>

                <ul>
                    <li>
                        <a href="@Url.Action("Index", "Formats")">
                            Спіс
                            <i class="zmdi  zmdi-view-list-alt zmdi-hc-lg"></i>
                        </a>
                    </li>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
                    {
                        <li>
                            <a href="@Url.Action("Create", "Formats")">
                                Стварыць
                                <i class="zmdi zmdi-plus-circle zmdi-hc-lg"></i>
                            </a>
                        </li>
                    }
                </ul>
            </li>

            <li>
                <a href="@Url.Action("Index", "Videos")">
                    Відыёзапісы
                    <i class="zmdi zmdi zmdi-videocam zmdi-hc-lg"></i>
                </a>


                <ul>
                    <li>
                        <a href="@Url.Action("Index", "Videos")">
                            Спіс
                            <i class="zmdi zmdi-view-list-alt  zmdi-hc-lg"></i>
                        </a>
                    </li>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
                    {
                        <li>
                            <a href="@Url.Action("Create", "Videos")">
                                Стварыць
                                <i class="zmdi zmdi-plus-circle zmdi-hc-lg"></i>
                            </a>
                        </li>
                    }

                </ul>

            </li>
        }





        <li id="profile">
            @(User?.Identity?.Name.Length > 0 ? User.Identity.Name : Html.Raw("Профіль").ToString())
            <i class="zmdi zmdi-account zmdi-hc-lg"></i>
            <i class="angle"></i>
        </li>
    </ul>
    @{ Html.RenderPartial("UserPanel", new LoginModel()); }
</div>

InfoVideo/Views/Shared/History.cshtml
@model IEnumerable<InfoVideo.Models.History>


<table class="table">
    <tr>
        <th>
            <a href="@Url.Action("Index", "Videos")" title="Змяніць">
                @Html.DisplayNameFor(model => model.Edition.Video)
            </a>
           
        </th>
        <th>
            <a href="@Url.Action("Index", "Formats")" title="Змяніць">
                @Html.DisplayNameFor(model => model.Edition.Format)
            </a>
        </th>
        <th>
            <a href="@Url.Action("Index", "Editions")" title="Змяніць">
                @Html.DisplayNameFor(model => model.Edition)
            </a>
          
        </th>
        <th>
            <a href="@Url.Action("Index", "Account")" title="Змяніць">
                @Html.DisplayNameFor(model => model.Users.Login)
            </a>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>

        <th></th>
    </tr>
  
@foreach (var item in Model)
{

  {
    <tr>
        <td>
            <a href="@Url.Action("Details", "Videos", new {id = item.Edition?.Video?.Id})" title="Змяніць">
                @Html.DisplayFor(modelItem => item.Edition.Video.Title)
            </a>

        </td>
        <td>
            <a href="@Url.Action("Details", "Formats", new {id = item.Edition?.Format?.Id})" title="Змяніць">
                @Html.DisplayFor(modelItem => item.Edition.Format.Languages)
            </a>

        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Edition.Box)
        </td>
        <td>
            <a href="@Url.Action("Details", "Account", new {id = item.Users?.Id})" title="Змяніць">
                @Html.DisplayFor(modelItem => item.Users.Login)
            </a>

        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price )
        </td>
        <td>
            <a href="@Url.Action("Edit", "Histories", new {id = item.Id})" title="Змяніць">
                <i class="zmdi zmdi-edit zmdi-hc-fw"></i>
            </a>
            <a href="@Url.Action("Details", "Histories", new {id = item.Id})" title="Падрабязнасці">
                <i class="zmdi zmdi-eye zmdi-hc-fw"></i>
            </a>

        </td>
    </tr>
}
      }

</table>

InfoVideo/Views/Shared/SidebarLeft.cshtml
    <div id='cssmenu'>
        <ul>
            <li><a href='@Url.Action("Index", "Home")'>На галоўную</a></li>
            <li class='active has-sub'>
                <a href='@Url.Action("Index", "Editions")'>Выданні</a>
                <ul>
                    <li class='has-sub'>
                        <a href='#'>Фэнтэзі</a>
                        <ul>
                            <li><a href='#'>The Shannara Chronicles</a></li>
                            <li><a href='#'>The 100</a></li>
                            <li><a href='#'>Stargate Atlantis</a></li>
                        </ul>
                    </li>
                    <li class='has-sub'>
                        <a href='#'>Шпіёнскія</a>
                        <ul>
                            <li><a href='#'>The Black List</a></li>
                            <li><a href='#'>Castle</a></li>
                        </ul>
                    <li class='has-sub'>
                        <a href='#'>Пажарныя</a>
                        <ul>
                            <li><a href='#'>Chicago Fire</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li><a href='@Url.Action("Index", "Account")'>Карыстачы</a></li>
            <li><a href='@Url.Action("Index", "Videos")'>Відыё</a></li>
            <li><a href='@Url.Action("Index", "Formats")'>Фарматы</a></li>
            <li><a href='@Url.Action("Index", "Histories")'>Гісторыя</a></li>
        </ul>
    </div>

InfoVideo/Views/Shared/SidebarRight.cshtml
@model IEnumerable<InfoVideo.Models.Video>


<div class="search card">
    @using (Ajax.BeginForm("ProcType", "Home",new { }, new AjaxOptions
    {
       
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "typeV"
    }, new { id = "searchForm" }))
    {

        @Html.TextBox("type", null, new { @placeholder = "Увядзіце фармат" })
        <label class="btn red" for="search">
            <i class="zmdi zmdi-search zmdi-hc-fw"></i>
        </label>
        <input type="submit" class="display-none" id="search" value="Search" />

    }
</div>

<div class="card" id="typeV"></div>
<div class="news" id="news">
    @foreach (var item in Model)
    {
        <div class="card">
            <i class="zmdi zmdi-menu menu-switch"></i>


            <img src="@Url.Content("~/Media/Images/" + item.Logo)" style="" alt="">
            <span class="title">@item.Title</span>

            <p>@Html.DisplayFor(t => item.Date)</p>
            <p>@item.Genre</p>


            <div class="menu-list card-menu" style="display: none">
                <ul>
                    <a href="@Url.Action("Details", "Videos", new {id = item.Id})">
                        <i class="zmdi zmdi-view-list-alt zmdi-hc-fw"></i>Падрабязнасці
                    </a>
                    <a href="@Url.Action("Edit", "Videos", new {id = item.Id})">
                        <i class="zmdi zmdi-edit zmdi-hc-fw"></i>Змяніць
                    </a>
                    <a href="@Url.Action("Delete", "Videos", new {id = item.Id})">
                        <i class="zmdi zmdi-delete zmdi-hc-fw"></i>Выдаліць
                    </a>
                </ul>

            </div>


        </div>

    }


</div>

InfoVideo/Views/Shared/Video.cshtml
@model InfoVideo.Models.Video

    <div class="item display-inline-block">
        <div class="item-header">
            <img src="@Url.Content("~/Media/Images/" + Model.Logo)" class="item-header-img" alt="">
            <h2 class="text-background top">@Model.Title</h2>
            <h3 class="text-background">
                @Model.Genre<br/>
                @Html.DisplayFor(t => Model.Date)
            </h3>
        </div>

        <div class="item-body">
            @Model.Description
        </div>

        <div class="item-footer">
          
                <a href="@Url.Action("Details", "Videos", new {id = Model.Id})">
                    <i class="zmdi zmdi-view-list-alt zmdi-hc-fw"></i>Падрабязнасці
                </a>
                <a href="@Url.Action("Edit", "Videos", new {id = Model.Id})">
                    <i class="zmdi zmdi-edit zmdi-hc-fw"></i>Змяніць
                </a>
                <a href="@Url.Action("Delete", "Videos", new {id = Model.Id})">
                    <i class="zmdi zmdi-delete zmdi-hc-fw"></i>Выдаліць
                </a>
            
        </div>
    </div>